name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Java 11 (matches your compileOptions/jvmTarget)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3. Cache Gradle dependencies and wrapper
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Ensure the Gradle wrapper is executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # 5. Build the debug APK
      - name: Assemble Debug
        run: ./gradlew :app:assembleDebug --no-daemon

      # 6. Run lint checks
      - name: Run lint
        run: ./gradlew :app:lintDebug --no-daemon

      # 7. Run unit tests
      - name: Run unit tests
        run: ./gradlew :app:testDebugUnitTest --no-daemon
